package paradigms.lab1;
/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int create = 1;
  /** RegularExpression Id. */
  int image = 2;
  /** RegularExpression Id. */
  int with = 3;
  /** RegularExpression Id. */
  int source = 4;
  /** RegularExpression Id. */
  int header = 5;
  /** RegularExpression Id. */
  int para = 6;
  /** RegularExpression Id. */
  int url = 7;
  /** RegularExpression Id. */
  int text = 8;
  /** RegularExpression Id. */
  int color = 9;
  /** RegularExpression Id. */
  int font = 10;
  /** RegularExpression Id. */
  int quote = 11;
  /** RegularExpression Id. */
  int and = 12;
  /** RegularExpression Id. */
  int nextLine = 13;
  /** RegularExpression Id. */
  int alphanumeric = 14;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"ADD\"",
    "\"IMAGE\"",
    "\"WITH\"",
    "\"SOURCE\"",
    "\"Heading\"",
    "\"PARAGRAPH\"",
    "\"LINK\"",
    "\"TEXT\"",
    "\"COLOR\"",
    "\"FONT\"",
    "\"\"",
    "\"AND\"",
    "\"\\n\"",
    "<alphanumeric>",
  };

}
